### PR TITLE
Dependencies of produced npm package now contain all required packages

### LINKED ISSUE #17: Publish NPM package with the right dependencies
The dependencies that were added (e.g. `@sentry/browser`) are available in the [`package.json`](https://github.com/ioBroker/adapter-react/blob/77226d075d5f1e4b9084a7d28d5585249f07d7b0/package.json#L26), but they are missing from the published npm package:
https://cdn.jsdelivr.net/npm/@iobroker/adapter-react/package.json

Can you please make sure they are published properly?

### PR DESCRIPTION
**Pull request by UncleSamSwiss**
(except for core React modules)

Tested with the current create-adapter version.

This will fix #17

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
@GermanBluefox please merge and release!

**Comment by GermanBluefox** [comment]
I don't understand, why are modules were removed...

**Comment by AlCalzone** [comment]
https://github.com/ioBroker/adapter-react/blob/26c10b9ac8efccfb67ac0de9bca24d5b854f65e3/package.json#L26-L33
They are included as dependencies in the `package.json` of this module. Once a dev has included `@iobroker/adapter-react`, he no longer has to add them to his own package.json.

**Comment by Apollon77** [comment]
LGTM

**Comment by GermanBluefox** [comment]
> https://github.com/ioBroker/adapter-react/blob/26c10b9ac8efccfb67ac0de9bca24d5b854f65e3/package.json#L26-L33
> 
> 
> They are included as dependencies in the `package.json` of this module (see gulpfile change). Once a dev has included `@iobroker/adapter-react`, he no longer has to add them to his own package.json, so it shouldn't be mentioned in the README.

But it is only valid, if the user uses dev server.

**Comment by AlCalzone** [comment]
> And why the gulp file takes and overwrite existing deps?

I don't understand. You use the gulpfile to release an npm package **without** `dependencies`, yet that npm package needs those dependencies to work. There are no dependencies that get overwritten.
Right now devs need to figure out which version of `adapter-react` needs which dependencies by going through the git history here and looking at the readme for the version they have installed. And they have to add them to their own package.json themselves.

The change here only makes it so the released npm package contains the correct dependencies, so this is no longer necessary.

**Comment by UncleSamSwiss** [comment]
> But it is only valid, if the user uses dev server. And why the gulp file takes and overwrite existing deps? And if I use something else? Maps, image processing? It will be overwritten by gulp task

This has nothing to do with dev-server. It is about using adapter-react with Adapter Creator. The dependencies you create in your package.json (while creating the adapter-react NPM package) are currently empty, thus as @AlCalzone said, every developer needs to add **your** dependencies as his dependencies. This is wrong. With npm, every package has its own dependencies, and those dependencies need to be mentioned in the package.json of the **published** npm package.

If you look at your published npm package, it has **no dependencies at all*: https://cdn.jsdelivr.net/npm/@iobroker/adapter-react/package.json

**Pull request merged**
